# Generated by Django 4.0.7 on 2023-09-02 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_creator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='creator_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=255)),
                ('venue', models.CharField(max_length=255)),
                ('event_date', models.DateField()),
                ('guests', models.CharField(max_length=255)),
                ('extpart', models.CharField(max_length=255)),
                ('intpart', models.EmailField(max_length=255)),
                ('spepoint', models.CharField(max_length=255)),
                ('highofthevent', models.CharField(max_length=255)),
                ('NoofIma', models.CharField(max_length=255)),
                ('UpIma', models.FileField(null=True, upload_to='')),
            ],
        ),
    ]
