# Generated by Django 4.0.7 on 2023-09-04 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_creator', '0004_creator_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='magazine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
            ],
        ),
    ]
