# Generated by Django 4.0.7 on 2023-09-04 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_creator', '0005_magazine'),
    ]

    operations = [
        migrations.DeleteModel(
            name='magazine',
        ),
    ]
