# Generated by Django 4.0.7 on 2023-09-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_creator', '0007_magazine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazine',
            name='content',
            field=models.TextField(),
        ),
    ]
