# Generated by Django 4.0.7 on 2023-09-04 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_creator', '0008_alter_magazine_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator_table',
            name='UpIma',
            field=models.ImageField(default='exit', upload_to='content_images'),
            preserve_default=False,
        ),
    ]
