# Generated by Django 4.0.7 on 2023-09-05 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_creator', '0009_alter_creator_table_upima'),
    ]

    operations = [
        migrations.DeleteModel(
            name='creator_table',
        ),
        migrations.DeleteModel(
            name='Magazine',
        ),
    ]
