# Generated by Django 4.0.7 on 2023-09-08 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_creator', '0011_creator_table_magazine'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator_table',
            name='UpIma1',
            field=models.ImageField(null=True, upload_to='content_images'),
        ),
        migrations.AddField(
            model_name='creator_table',
            name='UpIma2',
            field=models.ImageField(null=True, upload_to='content_images'),
        ),
    ]
