# Generated by Django 4.0.7 on 2023-09-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_creator', '0013_creator_table_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='template_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_name', models.CharField(max_length=255)),
                ('UpIma', models.ImageField(upload_to='template_img')),
            ],
        ),
    ]
