# Generated by Django 4.0.7 on 2023-09-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_creator', '0014_template_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='template_images',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
