# Generated by Django 4.0.7 on 2023-11-23 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_creator', '0022_delete_creator_table_delete_magazine'),
    ]

    operations = [
        migrations.CreateModel(
            name='creator_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=255)),
                ('venue', models.CharField(max_length=255)),
                ('event_date', models.DateField()),
                ('guests', models.CharField(max_length=255)),
                ('extpart', models.CharField(max_length=255)),
                ('intpart', models.EmailField(max_length=255)),
                ('spepoint', models.CharField(max_length=255)),
                ('highofthevent', models.CharField(max_length=255)),
                ('NoofIma', models.CharField(max_length=255)),
                ('UpIma', models.ImageField(upload_to='content_images')),
                ('UpIma1', models.ImageField(null=True, upload_to='content_images')),
                ('UpIma2', models.ImageField(null=True, upload_to='content_images')),
                ('template', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
    ]
